table 'Sales Change'

    column 'Sales Change'
        dataType: double
        sourceColumn: 'Sales Change'
        summarizeBy: none

    measure 'Sales Change Value' = SELECTEDVALUE('Sales Change'['Sales Change'], 0)
        formatString: 0.00

    partition 'Sales Change-Partition' = m
        mode: import
        source =
            GENERATESERIES(-1, 1, 0.01)

    annotation PBI_FormatHint = {"isGeneralNumber":true}